import { useEffect, useMemo, useState } from "react";
import { getCompanies } from "../services/companyService";
import { apiErrorMessage } from "../services/api";
import SearchBar from "../components/SearchBar";
import FilterBar from "../components/FilterBar";
import CompanyTable from "../components/CompanyTable";
import LoadingState from "../components/LoadingState";
import EmptyState from "../components/EmptyState";
import ErrorState from "../components/ErrorState";
const options=[["score","Prospect score"],["relevance","CSR relevance"],["spend","Historical spend"],["average","Average project spend"],["projects","Project count"]];
export default function Companies(){const [items,setItems]=useState(null),[error,setError]=useState(""),[search,setSearch]=useState(""),[type,setType]=useState(""),[sort,setSort]=useState("score"),[page,setPage]=useState(1);const pageSize=10;const load=async()=>{setError("");try{const {data}=await getCompanies();setItems(data.companies||[])}catch(e){setError(apiErrorMessage(e))}};useEffect(()=>{load()},[]);const types=useMemo(()=>[...new Set((items||[]).map(x=>x.companyType).filter(Boolean))],[items]);const filtered=useMemo(()=>{const key={score:"donorScore",relevance:"csrRelevance",spend:"totalCsrAmount",average:"averageProjectSpend",projects:"totalProjects"}[sort];return (items||[]).filter(x=>(x.companyName||"").toLowerCase().includes(search.toLowerCase())&&(!type||x.companyType===type)).sort((a,b)=>(Number(b[key])||0)-(Number(a[key])||0))},[items,search,type,sort]);useEffect(()=>setPage(1),[search,type,sort]);if(items===null&&!error)return <LoadingState label="Loading analyzed companies…"/>;if(error)return <ErrorState message={error} retry={load}/>;return <><section className="page-intro row"><div><p className="eyebrow">COMPANY DIRECTORY</p><h2>Analyze every opportunity.</h2><p>Explore the companies returned by your backend’s CSR analysis database.</p></div><span className="count-pill">{items.length} companies</span></section><div className="controls glass"><SearchBar value={search} onChange={setSearch}/><FilterBar types={types} type={type} onType={setType} sort={sort} onSort={setSort} sortOptions={options}/></div>{filtered.length?<><CompanyTable companies={filtered.slice((page-1)*pageSize,page*pageSize)} startRank={(page-1)*pageSize}/><Pagination page={page} total={filtered.length} size={pageSize} setPage={setPage}/></>:<EmptyState title="No companies found." text="Try a different search or filter."/>}</>}
export function Pagination({page,total,size,setPage}){const pages=Math.ceil(total/size);return pages>1?<div className="pagination"><button disabled={page===1} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page} of {pages}</span><button disabled={page===pages} onClick={()=>setPage(page+1)}>Next</button></div>:null}
