import { useEffect, useMemo, useState } from "react";
import { Building2, CircleDollarSign, Compass, FolderKanban, Sparkles, Target } from "lucide-react";
import { Link } from "react-router-dom";
import { BarChart, Bar, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { getCompanies } from "../services/companyService";
import { apiErrorMessage } from "../services/api";
import StatCard from "../components/StatCard";
import CompanyTable from "../components/CompanyTable";
import EmptyState from "../components/EmptyState";
import ErrorState from "../components/ErrorState";
import LoadingState from "../components/LoadingState";
const avg = (items, key) => { const values = items.map(x => Number(x[key])).filter(Number.isFinite); return values.length ? values.reduce((a,b) => a + b, 0) / values.length : null; };
export default function Dashboard() { const [companies, setCompanies] = useState(null); const [error, setError] = useState(""); const load = async () => { setError(""); try { const { data } = await getCompanies(); setCompanies(data.companies || []); } catch (e) { setError(apiErrorMessage(e)); } }; useEffect(() => { load(); }, []);
  const stats = useMemo(() => { if (!companies) return []; const totalSpend = companies.map(x => Number(x.totalCsrAmount)).filter(Number.isFinite).reduce((a,b)=>a+b,0); return [["Total companies", companies.length, Building2], ["Total projects", companies.reduce((a,x) => a + (Number(x.totalProjects) || 0), 0), FolderKanban], ["Average donor score", avg(companies,"donorScore")?.toFixed(1) ?? "N/A", Target], ["Average CSR relevance", avg(companies,"csrRelevance")?.toFixed(1) ?? "N/A", Compass], ["Historical CSR spend", totalSpend ? `₹ ${totalSpend.toLocaleString()}` : "N/A", CircleDollarSign], ["High-potential", companies.filter(x => x.donorPotential === "HIGH").length, Sparkles]]; }, [companies]);
  const typeData = useMemo(() => !companies ? [] : Object.entries(companies.reduce((o,c) => { const type=c.companyType || "Unknown"; o[type]=(o[type] || 0)+1; return o; }, {})).map(([name,value]) => ({name,value})), [companies]);
  if (companies === null && !error) return <LoadingState label="Loading company intelligence…"/>; if (error) return <ErrorState message={error} retry={load}/>; if (!companies.length) return <EmptyState title="No CSR dataset analyzed yet." text="Upload a historical CSR dataset to start identifying potential donors." action={<Link className="button" to="/upload">Analyze CSR dataset</Link>}/>;
  return <><section className="hero"><div><p className="eyebrow">LIVE DATA OVERVIEW</p><h2>Make your next CSR partnership <em>more intentional.</em></h2><p>Decision-ready donor intelligence, calculated only from your analyzed dataset.</p></div><Link className="button" to="/upload">Analyze another dataset</Link></section><section className="stat-grid">{stats.map(([label,value,icon]) => <StatCard key={label} label={label} value={value} icon={icon}/>)}</section><section className="dashboard-grid"><article className="panel glass chart-panel"><div className="panel-heading"><div><p className="eyebrow">DISTRIBUTION</p><h2>Companies by type</h2></div></div>{typeData.length ? <ResponsiveContainer width="100%" height={260}><BarChart data={typeData}><XAxis dataKey="name" stroke="#9bb1c9"/><YAxis allowDecimals={false} stroke="#9bb1c9"/><Tooltip contentStyle={{background:"#10243d",border:"1px solid #31506e",borderRadius:12}}/><Bar dataKey="value" radius={[7,7,0,0]} fill="#35d7c5"/></BarChart></ResponsiveContainer> : <p>Not enough data available for this visualization.</p>}</article><article className="panel glass focus-panel"><p className="eyebrow">WHAT’S NEXT</p><h2>Explore the strongest matches</h2><p>Find organizations currently marked as high donor potential by your analysis pipeline.</p><Link className="text-link" to="/leads">Open donor leads →</Link></article></section><section className="panel glass"><div className="panel-heading"><div><p className="eyebrow">TOP PROSPECTS</p><h2>Highest donor scores</h2></div><Link className="text-link" to="/companies">View all companies →</Link></div><CompanyTable companies={[...companies].sort((a,b)=>(b.donorScore||0)-(a.donorScore||0)).slice(0,5)}/></section></>; }
